title = "Abhayraj Jain"
baseURL = "https://abhayraj.net/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true

[params]
address = "Hamilton, ON"
email = "hello@abhayraj.net"
favicon = "/favicon.ico"
firstName = "Abhayraj"
lastName = "Jain"
phone = "1-365-777-1613"
profileImage = "img/profile.jpg"
showEducation = true
showExperience = true
showProjects = false
showGraphics = false
showWritten = false
showSkills = true
showQr = false
showBlog = false

[params.google]

[params.google.analytics]
trackerID = "G-63RXG3TXR4"

[[params.handles]]
link = "https://www.linkedin.com/in/abhayrajjain/"
name = "LinkedIn"
icontag = "LinkedIn"

[[params.handles]]
link = "/Abhayraj_Jain_Resume.pdf"
name = "PDF Resume"
icontag = "black-tie"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"