title = "Abhayraj Jain"
baseURL = "https://abhaytest.netlify.app/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true

[params]
address = "Hamilton, ON"
email = "college@abhayraj.net"
favicon = "/favicon.ico"
firstName = "Abhayraj"
lastName = "Jain"
phone = "1-365-777-1613"
profileImage = "img/profile.jpg"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = true
showQr = false
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "UA-108350429-01"

[[params.handles]]
link = "https://www.linkedin.com/in/abhayrajjain/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/nanzer/"
name = "GitHub"


[[params.handles]]
link = "https://abhayraj.net/resume.pdf"
name = "PDF"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"